### PR TITLE
alsa function update

### PR DESCRIPTION
**Pull request by ryankojima**
Compatibility update for new ALSA function

### CODE REVIEW

**Comment by ao2** [comment]
If you need this change it means that you want to use a newer kernel which should already have the hiface driver, so it makes no sense to add this change to the old out-of-tree driver.

See https://github.com/panicking/snd-usb-asyncaudio/pull/4

With what version of the kernel do you want to use this driver?

**Comment by ryankojima** [comment]
Oh I didn't know about this. I tried with 3.18 (in Volumio) but kernel didn't recognize Hiface 1 so I installed it manually. According to your link 3.18 should include the module?

**Comment by ryankojima** [comment]
But if it's in kernel already, maybe it was my configuration issue. Please discard this request.

**Comment by ao2** [comment]
Just enable SND_USB_HIFACE in the kernel config, or ask your distribution to do so.

**Pull request closed without merging**
